---
title: "Assignment 4: Study designs"
format: html
editor_options: 
  chunk_output_type: console
bibliography: 04_study_designs.bib
---


## Introduksjon

Studiedesign er en viktig komponent i forskning da det vil være avgjørende for hvordan data samles inn, tolkes og analyseres. Et godt studiedesign vil ofte resultere i mer pålitelige resultater og større grad av reproduserbarhet. Studier som ser seg mer anvendbare i praksis er å foretrekke. [@Zabor2020]

Struktur er en viktig komponent når man planlegger en studie. QALMRI-metoden kan bidra til å sikre en ryddig og god struktur. QALMRI adresserer spørsmål som en ønsker svar på, for så å oppgi hvilke tilnærminger som skal benyttes for å besvare spørsmålet. Videre ser man på sammenhengen mellom metodene som benyttes i studien og koblingen til spørsmålet, eller hypotesten, man har stilt i oppgaven. Til slutt presenteres resultatene og man drar konklusjoner til den aktuelle populasjonen. 

I denne oppgaven studeres fem originalartikler som tar for seg effekten av blokkperiodisering på $\dot{V}O_{2max}$ [@Ronnestad2019], [@Breil2010], [@Ronnestad2016], [@Ronnestad2014], [@Ronnestad2014_2]. I oppgaven blir det lagt mest vekt på studiedesignene og de statistiske analysemetodene fra de utvalgte studiene, samt en vurdering av styrker og svakheter knyttet til disse. 

## Metode

Alle studiene i oppgaven er randomiserte kontrollerte forsøk (RCT) der man var interessert i å undersøke effekten av periodisering av høyintensiv trening. Utvalget ble delt i to grupper, en  blokkperiodiseringsgruppe (BP) og en kontrollgruppe (CT). I studiene trente utvalget i BP og CT det samme volumet totalt over intervensjonsperioden. Forskjellen var at BP periodiserte sine høyintesive økter i bolker/mikrosykluser (periodiserignen varierte mellom studiene). Det ble gjennomført målinger både pre og post treningsintervensjonen og intervensjonene hadde varighet fra 4 til 12 uker.

I studiene lå utvalget et sted mellom 16 og 22 personer. I noen studier så en på både kvinner og menn, i andre studier kun menn. Gjengangeren var at utvalget ble definert som godt trente utøvere, eller at de hadde drevet kompetetivt i sin idrett de siste årene.

Det ble gjennomført ulike statistiske analyser i de ulike forsøkene. Noen benyttet ANOVA, mens andre benyttet t-tester, eller en kombinasjon av begge. Flere av studiene benyttet Cohen's d for å beregne effektstørrelse (ES) da dette er en gunstig metode når man vil vurdere effekten av en intervensjon og sammenlinkne to grupper [@Hopkins2009]. I studiene ble resultater presentert som gjennomsnittsøkning i % $\pm$ standardavvik. Resultater ble ansett som statistisk signifikante dersom *p*-verdier $\leq$ 0.05. 

## Resultater

Etter å ha sammenliknet kontrollgruppen med blokkperiodiseringsgruppen post intervensjon, kom samtlige studier frem til at blokkperiodisering gav signinfikant økning i prestasjonsparametere. Økningen i $\dot{V}O_{2max}$ ble presentert til å ligge mellom 6.0-8.8 % blant studiene. 

*P*-verdier < 0.05 i samtlige studier. Den gjennomsnittlige effekten blir målt til å ligge en plass mellom 0.76 og 1.34 i 4/5 studier. En av studiene gjorde i tillegg beregninger på kun de mannlige utøverne i sin studie og fant mer signifikante resultater. Denne studien presenterte ingen effektstørrelser.  

## Diskusjon


Styrken ved å benytte RCT som studiedesign er at det minimerer bias og skaper godt sammenlikningsgrunnlag blant liknende intervensjoner. Ved å benytte RCT blir også resultatene mer pålitelige. Ved å benytte objektive data i sine resultater, skapes en anvendbarhet i form av at studiene i større grad er sammenliknbare på tvers av studier og intervensjoner. [@Zabor2020]

En svakhet ved studiene er de små utvalgene. Dette øker sjansen for å gjøre type II-feil (godtakelse av nullhypotesen, tross at den er falsk). Gjennomsnitt i små utvalg påvirkes i relativt stor grad av verdier som ligger langt unna gjennomsnittet (outliers) [@Mishra2019]. For å objektivt fjerne outliers fra datasettet kan en bestemme seg for grenseverdier man ønsker at sine verdier skal ligge innenfor [@Hopkins2009].  

Det kan tenkes at det er gunstig for fremtidige studier å ha større grad av mangfold, dvs. menn og kvinner, ulik alder og treningsbakgrunn. Dette for å kunne si noe om en bredere populasjon. Utvalget bør dog stå i stil til populasjonen man ønsker å si noe om. Ønsker man eksempelvis å forskrive gode treningsmetoder for toppidrettsutøvere innen sykkelsporten, bør utvalget bestå at godt trente syklister. Da utvalgene i disse studiene bestod av godt trente utøvere, kan det antyde at blokkperiodisering av høyintensiv trening kan være gunstig for utøvere som allerede er på et høyt nivå. 

Tid og varighet av intervensjoner er ofte en svakhet i studier. Disse studiene varte i hhv. 5-, 4-, 5-, 6- og 12-uker, noe som gjør det vanskelig å si noe om de langsiktige effektene av blokkperiodisering vs tradisjonell trening. Funnene i studiene kan styrkes dersom man studiene repeteres og/eller følges opp over lengre perioder. 

Målet med studiene var å se hvorvidt mikrosykluser med høyintensiv trening øker prestasjonsparameteren $\dot{V}O_{2max}$ mer enn traidisjonell periodisering av trening. For å undersøke potensielle endringer mellom BP og CT i studiene ble det som nevnt benyttet ulike statistsike tester. Grunnet små utvalg og en forventet liten endring i prestasjonsmaraterne blant de godt trente utøverne, ble det benyttet t-tester da det viser seg hensiksmessig ved små utvalg og benyttes for å sammenlikne gjennomsnittet mellom to grupper [@Mishra2019].  

Det at én av studiene ikke presenterte effektstørrelse kan man stille spørmål ved. En av grunnene kan være at små utvalg kan skape store variasjoner i resultater og skape lite pålitelige effekter. Et annet punkt å diskutere er hvorvidt resulatene er av klinisk relevans. Dersom forskerne mener at en effektsørrelsen kan gi et feilaktig inntrykk av resultatenes styrke, kan de la være å presentere effekten. 

## Konklusjon

Blokkperiodisering viser å gi større økning i $\dot{V}O_{2max}$ i samtlige studier, sammenliknet med tradisjonell trening. Langrennsutøvere, ishockeyspillere, alpinister og syklister har alle hatt økning i $\dot{V}O_{2max}$ ved å periodisere hard trening. Godt trente utøvere, som potensielt har stagnert med tradisjonell trening, kan ha god effekt av blokkperiodisering. Funnene vil særlig være relevant for godt trente utøvere, da dette var utvalget som ble sett på i samtlige studier. Dette er dog et snevert utvalg, som trolig har egenskaper som skiller seg fra resten av befolkningen. Derfor vil det være utfordrende å generalisere funn og anbefalinger opp mot den generelle befolkningen. Repetisjon av studiene der utvalget innehar større grad av spredning når det kommer til treningsbakgrunn, kjønn og alder kan derav være av interesse. 

Alle studiene er randomiserte kontrollerte studier, noe som gir tyngde til grad av validitet og grunnlag for direkte sammenlikning av ulike treningsmetoder. Det parallelle gruppedesignet som ble benyttet isolerer effekten av de ulike treningsintervensjonene.  

ANOVA (analysis of variance) og *t*-tester ble benyttet slik at man kan sammenlikne flere grupper over ulike tidpunkter i intervensjonen. På den måten kan man få innblikk i hvordan ulik form for trening påvirker prestasjonparametere over tid. Valget av testene bidrar å styrke funnene om at blokkperiodisering gir økning i $\dot{V}O_{2max}$, sammenliknet med tradisjonell trening. 


## Referanser


